--- #YAML:1.0
name:               IPTables-libiptc
version:            0.52
abstract:           Perl extension for iptables libiptc
author:
    - Jesper Dangaard Brouer <hawk@comx.dk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
